name: dbt_ai_teammate
version: "1.0.0"
config-version: 2

profile: dbt_ai_teammate

model-paths:
  - models

seed-paths:
  - seeds

target-path: target

clean-targets:
  - target

models:
  dbt_ai_teammate:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table
